#!/usr/bin/env bash
#
# Bitly = https://raw.githubusercontent.com/tallguyjenks/BusinessCard/master/business_card
#
# Write a nice business card on the terminal.
# ╭───────────────────────────────────────────────────────╮
# │                                                       │
# │           Michael Tsouchlarakis / michaeltd           │
# │                                                       │
# │      Work:  tsouchlarakis@gmail.com                   │
# │      FOSS:  Gentoo Linux avocado.                     │
# │                                                       │
# │   Twitter:  https://twitter.com/tsouchlarakismd       │
# │       npm:  https://npmjs.com/~michaeltd              │
# │    GitHub:  https://github.com/michaeltd              │
# │  LinkedIn:  https://linkedin.com/in/michaeltd         │
# │       Web:  https://michaeltd.netlify.com/            │
# │                                                       │
# │      Card:  curl -sL https://tinyurl.com/mtd-card|sh  │
# │                                                       │
# ╰───────────────────────────────────────────────────────╯
# Font attributes, colors, bg colors
reset='\e[0m'
bold='\e[1m'
dim='\e[2m'
underline='\e[4m'
red='\e[0;31m'
green='\e[0;32m'
yellow='\e[0;33m'
blue='\e[0;34m'
magenta='\e[0;35m'
cyan='\e[0;36m'

echo -e "\n
${cyan}╭───────────────────────────────────────────────────────╮
${cyan}│                                                       │
${cyan}│${reset}           ${cyan}${bold}Bryan Jenks / TallGuyJenks${reset}                  ${cyan}│
${cyan}│                                                       │
${cyan}│${reset}     ${underline}${bold}Email:${reset}  ${magenta}bryanjenks@protonmail.com${reset}                 ${cyan}│
${cyan}│${reset}       ${underline}${bold}Web:${reset}  ${dim}https://www.${reset}${cyan}bryanjenks.xyz                ${cyan}│
${cyan}│                                                       │
${cyan}│${reset}   ${underline}${bold}Twitter:${reset}  ${dim}https://twitter.com/${reset}${blue}Tall_Viking           ${cyan}│
${cyan}│${reset}    ${underline}${bold}GitHub:${reset}  ${dim}https://github.com/${reset}${green}tallguyjenks           ${cyan}│
${cyan}│${reset}  ${underline}${bold}LinkedIn:${reset}  ${dim}https://linkedin.com/in/${reset}${blue}bryanjenks        ${cyan}│
${cyan}│${reset}   ${underline}${bold}YouTube:${reset}  ${dim}https://www.youtube.com/c/${reset}${red}BryanJenksTech  ${cyan}│
${cyan}│${reset}    ${underline}${bold}OrchID:${reset}  ${dim}https://orcid.org/${reset}${green}0000-0002-9604-3069     ${cyan}│
${cyan}│${reset}   ${underline}${bold}Patreon:${reset}  ${dim}https://www.patreon.com/${reset}${yellow}bryanjenks        ${cyan}│
${cyan}│                                                       │
${cyan}│${reset}      ${underline}${bold}Card:${reset}  ${yellow}curl -sL bit.ly/2zvxUbd                   ${cyan}│
${cyan}│                                                       │
${cyan}╰───────────────────────────────────────────────────────╯

"
