#!/usr/bin/env bash
#
# Bitly = https://raw.githubusercontent.com/tallguyjenks/BusinessCard/master/business_card
#
# Write a nice business card on the terminal.
# ╭───────────────────────────────────────────────────────╮
# │                                                       │
# │           Michael Tsouchlarakis / michaeltd           │
# │                                                       │
# │      Work:  tsouchlarakis@gmail.com                   │
# │      FOSS:  Gentoo Linux avocado.                     │
# │                                                       │
# │   Twitter:  https://twitter.com/tsouchlarakismd       │
# │       npm:  https://npmjs.com/~michaeltd              │
# │    GitHub:  https://github.com/michaeltd              │
# │  LinkedIn:  https://linkedin.com/in/michaeltd         │
# │       Web:  https://michaeltd.netlify.com/            │
# │                                                       │
# │      Card:  curl -sL https://tinyurl.com/mtd-card|sh  │
# │                                                       │
# ╰───────────────────────────────────────────────────────╯
# Font attributes, colors, bg colors
reset='\a'
bold='\e[1m'
dim='\e[2m'
#blink="$(tput blink)"
underline="$(tput smul)"
#end_underline="$(tput rmul)"
#reverse="$(tput rev)"
#hidden="$(tput invis)"
#black="$(tput setaf 0)"
red="$(tput setaf 1)"
green="$(tput setaf 2)"
yellow="$(tput setaf 3)"
blue="$(tput setaf 4)"
magenta="$(tput setaf 5)"
cyan='\e[0;36m'
#white="$(tput setaf 7)"
#default="$(tput setaf 9)"
#bg_black="$(tput setab 0)"
#bg_red="$(tput setab 1)"
#bg_green="$(tput setab 2)"
#bg_yellow="$(tput setab 3)"
#bg_blue="$(tput setab 4)"
#bg_magenta="$(tput setab 5)"
#bg_cyan="$(tput setab 6)"
#bg_white="$(tput setab 7)"
#bg_default="$(tput setab 9)"

#cat <<EOF

${cyan}╭───────────────────────────────────────────────────────╮${reset}
${cyan}│                                                       │
${cyan}│${reset}           ${bold}${cyan}Bryan Jenks / TallGuyJenks${reset}                  ${cyan}│
${cyan}│                                                       │
${cyan}│${reset}     ${underline}${bold}Email:${reset}  ${magenta}bryanjenks@protonmail.com                 ${cyan}│
${cyan}│${reset}       ${underline}${bold}Web:${reset}  ${dim}https://www.${reset}${cyan}bryanjenks.xyz                ${cyan}│
${cyan}│                                                       │
${cyan}│${reset}   ${underline}${bold}Twitter:${reset}  ${dim}https://twitter.com/${reset}${blue}Tall_Viking           ${cyan}│
${cyan}│${reset}    ${underline}${bold}GitHub:${reset}  ${dim}https://github.com/${reset}${green}tallguyjenks           ${cyan}│
${cyan}│${reset}  ${underline}${bold}LinkedIn:${reset}  ${dim}https://linkedin.com/in/${reset}${blue}bryanjenks        ${cyan}│
${cyan}│${reset}   ${underline}${bold}YouTube:${reset}  ${dim}https://www.youtube.com/c/${reset}${red}BryanJenksTech  ${cyan}│
${cyan}│${reset}    ${underline}${bold}OrchID:${reset}  ${dim}https://orcid.org/${reset}${green}0000-0002-9604-3069     ${cyan}│
${cyan}│${reset}   ${underline}${bold}Patreon:${reset}  ${dim}https://www.patreon.com/${reset}${yellow}bryanjenks        ${cyan}│
${cyan}│                                                       │
${cyan}│${reset}      ${underline}${bold}Card:${reset}  ${yellow}curl -sL bit.ly/2zvxUbd                  ${cyan}│
${cyan}│                                                       │
${cyan}╰───────────────────────────────────────────────────────╯

#EOF

